// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerLibrary.Data;

#nullable disable

namespace ServerLibrary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250218074624_first-rm-contactcustomers-id")]
    partial class firstrmcontactcustomersid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ContactCustomer", b =>
                {
                    b.Property<int>("ContactsId")
                        .HasColumnType("int");

                    b.Property<int>("CustomersId")
                        .HasColumnType("int");

                    b.HasKey("ContactsId", "CustomersId");

                    b.HasIndex("CustomersId");

                    b.ToTable("ContactCustomer");
                });

            modelBuilder.Entity("Data.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("DueDate")
                        .HasColumnType("longtext");

                    b.Property<string>("EndTime")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModuleType")
                        .HasColumnType("int");

                    b.Property<string>("ModuleTypeText")
                        .HasColumnType("longtext");

                    b.Property<string>("Place")
                        .HasColumnType("longtext");

                    b.Property<string>("StartTimeCustom")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Data.Entities.ActivityEmployees", b =>
                {
                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.HasKey("ActivityId", "EmployeeId", "PartnerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PartnerId");

                    b.ToTable("ActivityEmployees");
                });

            modelBuilder.Entity("Data.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsActivateEmail")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("Data.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountTypeID")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactCode")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("longtext");

                    b.Property<string>("DepartmentID")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool?>("EmailOptOut")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("LeadSourceID")
                        .HasColumnType("longtext");

                    b.Property<string>("MailingDistrictID")
                        .HasColumnType("longtext");

                    b.Property<string>("MailingProvinceID")
                        .HasColumnType("longtext");

                    b.Property<string>("MailingStreet")
                        .HasColumnType("longtext");

                    b.Property<string>("MailingWardID")
                        .HasColumnType("longtext");

                    b.Property<string>("MailingZip")
                        .HasColumnType("longtext");

                    b.Property<string>("Mobile")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OfficeEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("OfficeTel")
                        .HasColumnType("longtext");

                    b.Property<string>("OtherPhone")
                        .HasColumnType("longtext");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<bool?>("PhoneOptOut")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SalutationID")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingDistrictID")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingProvinceID")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingStreet")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingWardID")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingZip")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleID")
                        .HasColumnType("longtext");

                    b.Property<string>("Zalo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Data.Entities.ContactEmployees", b =>
                {
                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.HasKey("ContactId", "EmployeeId", "PartnerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PartnerId");

                    b.ToTable("ContactEmployees");
                });

            modelBuilder.Entity("Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("AccountReferredID")
                        .HasColumnType("longtext");

                    b.Property<string>("AccountShortName")
                        .HasColumnType("longtext");

                    b.Property<string>("AccountTypeID")
                        .HasColumnType("longtext");

                    b.Property<string>("AnnualRevenueID")
                        .HasColumnType("longtext");

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext");

                    b.Property<string>("BankAccount")
                        .HasColumnType("longtext");

                    b.Property<string>("BankName")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingCode")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingCountryID")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingDistrictID")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingLat")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingLong")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingProvinceID")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingStreet")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingWardID")
                        .HasColumnType("longtext");

                    b.Property<string>("BudgetCode")
                        .HasColumnType("longtext");

                    b.Property<string>("BusinessTypeID")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CelebrateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ContactIDAim")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CustomerSinceDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Debt")
                        .HasColumnType("longtext");

                    b.Property<string>("DebtLimit")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Fax")
                        .HasColumnType("longtext");

                    b.Property<string>("GenderID")
                        .HasColumnType("longtext");

                    b.Property<string>("Identification")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Inactive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IndustryID")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDistributor")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOldCustomer")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPartner")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPersonal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastVisitDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Latitude")
                        .HasColumnType("longtext");

                    b.Property<string>("LeadSourceID")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NoOfEmployeeID")
                        .HasColumnType("longtext");

                    b.Property<string>("NumberOfDaysOwed")
                        .HasColumnType("longtext");

                    b.Property<string>("OfficeEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("OfficeTel")
                        .HasColumnType("longtext");

                    b.Property<string>("OrganizationUnitID")
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerID")
                        .HasColumnType("longtext");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("RevenueDetail")
                        .HasColumnType("longtext");

                    b.Property<string>("SectorText")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingCode")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingCountryID")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingDistrictID")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingLat")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingLong")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingProvinceID")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingStreet")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingWardID")
                        .HasColumnType("longtext");

                    b.Property<string>("TaxCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Website")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Data.Entities.CustomerEmployees", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "EmployeeId", "PartnerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PartnerId");

                    b.ToTable("CustomerEmployees");
                });

            modelBuilder.Entity("Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Fullname")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("JobTitle")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Province")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SignedContractDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("TaxIdentificationNumber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Data.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AmountSummary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("BankAccount")
                        .HasColumnType("longtext");

                    b.Property<string>("BankName")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingCode")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingCountryID")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingDistrictID")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingLat")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingLong")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingProvinceID")
                        .HasColumnType("longtext");

                    b.Property<int?>("BuyerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrencyTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<double?>("DiscountSummary")
                        .HasColumnType("double");

                    b.Property<string>("InvoiceAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("InvoiceRequestName")
                        .HasColumnType("longtext");

                    b.Property<string>("InvoiceTypeId")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsInvoicePaper")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentTypeId")
                        .HasColumnType("longtext");

                    b.Property<string>("RecipientEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("RecipientName")
                        .HasColumnType("longtext");

                    b.Property<string>("RecipientPhone")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StatusID")
                        .HasColumnType("longtext");

                    b.Property<string>("TaxBudgetCode")
                        .HasColumnType("longtext");

                    b.Property<double?>("TaxSummary")
                        .HasColumnType("double");

                    b.Property<decimal?>("ToCurrencyAfterDiscountSummary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ToCurrencySummary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalSummary")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Data.Entities.InvoiceEmployees", b =>
                {
                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.HasKey("InvoiceId", "EmployeeId", "PartnerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PartnerId");

                    b.ToTable("InvoiceEmployees");
                });

            modelBuilder.Entity("Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BalanceReceiptAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("BillingAccountID")
                        .HasColumnType("int");

                    b.Property<string>("BillingAccountIDText")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingCode")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingContactID")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingCountryID")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingDistrictID")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingProvinceID")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingStreet")
                        .HasColumnType("longtext");

                    b.Property<string>("BillingWardID")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("BookDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("ContactName")
                        .HasColumnType("longtext");

                    b.Property<string>("ContractNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeadlineDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeliveryStatusID")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("DiscountAfterTaxSummary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("DiscountSummary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceReceivingEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("InvoiceReceivingPhone")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("InvoicedAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool?>("IsContractPartner")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsInvoiced")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsSentBill")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsShared")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("LiquidateAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("NotPaidAmountSummary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("NumberOfDaysOwed")
                        .HasColumnType("int");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PaidAmountSummary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("PayStatusID")
                        .HasColumnType("longtext");

                    b.Property<string>("PayStatusIDText")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("RecordedSale")
                        .HasColumnType("longtext");

                    b.Property<string>("RecordedSaleOrganizationUnitID")
                        .HasColumnType("longtext");

                    b.Property<string>("RecordedSaleUsersID")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("RemainingAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ReturnedSummary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("RevenueAccountingAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("RevenueRecognitionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RevenueStatusID")
                        .HasColumnType("longtext");

                    b.Property<decimal>("SaleOrderAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("SaleOrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SaleOrderName")
                        .HasColumnType("longtext");

                    b.Property<string>("SaleOrderNo")
                        .HasColumnType("longtext");

                    b.Property<double>("SaleOrderProcessCost")
                        .HasColumnType("double");

                    b.Property<string>("SaleOrderTypeID")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingCode")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingContactID")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingCountryID")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingDistrictID")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingProvinceID")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingReceivingPerson")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingStreet")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingWardID")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusID")
                        .HasColumnType("longtext");

                    b.Property<string>("TaxCode")
                        .HasColumnType("longtext");

                    b.Property<double?>("TaxSummary")
                        .HasColumnType("double");

                    b.Property<decimal?>("ToCurrencySummary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalReceiptedAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalSummary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("UnInvoicedAmount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PartnerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Data.Entities.OrderEmployees", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "EmployeeId", "PartnerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PartnerId");

                    b.ToTable("OrderEmployees");
                });

            modelBuilder.Entity("Data.Entities.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailContact")
                        .HasColumnType("longtext");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortName")
                        .HasColumnType("longtext");

                    b.Property<string>("TaxIdentificationNumber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("Data.Entities.PartnerUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.HasIndex("UserId");

                    b.ToTable("PartnerUsers");
                });

            modelBuilder.Entity("Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AmountSummary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ConversionRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ConversionUnit")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Equation")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Inactive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("InventoryItemID")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFollowSerialNumber")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSetProduct")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsSystem")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsUseTax")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OldProductCode")
                        .HasColumnType("longtext");

                    b.Property<string>("OperatorID")
                        .HasColumnType("longtext");

                    b.Property<int?>("OwnerID")
                        .HasColumnType("int");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<bool>("PriceAfterTax")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProductGroupID")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductGroupName")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductPropertiesID")
                        .HasColumnType("longtext");

                    b.Property<decimal>("PurchasedPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("QuantityDemanded")
                        .HasColumnType("int");

                    b.Property<string>("QuantityFormula")
                        .HasColumnType("longtext");

                    b.Property<int?>("QuantityInstock")
                        .HasColumnType("int");

                    b.Property<int?>("QuantityOrdered")
                        .HasColumnType("int");

                    b.Property<string>("SaleDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("SearchTagID")
                        .HasColumnType("longtext");

                    b.Property<string>("TagColor")
                        .HasColumnType("longtext");

                    b.Property<string>("TagID")
                        .HasColumnType("longtext");

                    b.Property<string>("TaxID")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Taxable")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("UnitPrice1")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("UnitPrice2")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("UnitPriceFixed")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("UsageUnitID")
                        .HasColumnType("longtext");

                    b.Property<string>("VendorNameID")
                        .HasColumnType("longtext");

                    b.Property<string>("WarrantyDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("WarrantyPeriod")
                        .HasColumnType("longtext");

                    b.Property<string>("WarrantyPeriodTypeID")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex(new[] { "ProductCode", "PartnerId" }, "Unique_ProductCode_PartnerId")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Data.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool?>("InActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("InventoryCategoryID")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentProductCategoryID")
                        .HasColumnType("int");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("ProductCategoryCode")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductCategoryName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ParentProductCategoryID");

                    b.HasIndex("PartnerId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Data.Entities.ProductEmployees", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "EmployeeId", "PartnerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PartnerId");

                    b.ToTable("ProductEmployees");
                });

            modelBuilder.Entity("Data.Entities.ProductInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("PurchasePrice")
                        .HasColumnType("double");

                    b.Property<int>("QuantitySold")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductInventories");
                });

            modelBuilder.Entity("Data.Entities.ProductPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPrices");
                });

            modelBuilder.Entity("Data.Entities.RefreshTokenInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokenInfos");
                });

            modelBuilder.Entity("Data.Entities.SystemRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SystemRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SysAdmin"
                        });
                });

            modelBuilder.Entity("Data.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("ContactCustomer", b =>
                {
                    b.HasOne("Data.Entities.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.Activity", b =>
                {
                    b.HasOne("Data.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Data.Entities.ActivityEmployees", b =>
                {
                    b.HasOne("Data.Entities.Activity", "Activity")
                        .WithMany("ActivityEmployees")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Employee", "Employee")
                        .WithMany("ActivityEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Entities.Partner", "Partner")
                        .WithMany("ActivityEmployees")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Employee");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Data.Entities.Contact", b =>
                {
                    b.HasOne("Data.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Data.Entities.ContactEmployees", b =>
                {
                    b.HasOne("Data.Entities.Contact", "Contact")
                        .WithMany("ContactEmployees")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Employee", "Employee")
                        .WithMany("ContactEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Entities.Partner", "Partner")
                        .WithMany("ContactEmployees")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Employee");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Data.Entities.Customer", b =>
                {
                    b.HasOne("Data.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Data.Entities.CustomerEmployees", b =>
                {
                    b.HasOne("Data.Entities.Customer", "Customer")
                        .WithMany("CustomerEmployees")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Employee", "Employee")
                        .WithMany("CustomerEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Entities.Partner", "Partner")
                        .WithMany("CustomerEmployees")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Data.Entities.Employee", b =>
                {
                    b.HasOne("Data.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Data.Entities.Invoice", b =>
                {
                    b.HasOne("Data.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Data.Entities.InvoiceEmployees", b =>
                {
                    b.HasOne("Data.Entities.Employee", "Employee")
                        .WithMany("InvoiceEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceEmployees")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Partner", "Partner")
                        .WithMany("InvoiceEmployees")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Invoice");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Data.Entities.Order", b =>
                {
                    b.HasOne("Data.Entities.Contact", null)
                        .WithMany("Orders")
                        .HasForeignKey("ContactId");

                    b.HasOne("Data.Entities.Customer", null)
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.HasOne("Data.Entities.Invoice", "Invoice")
                        .WithMany("Orders")
                        .HasForeignKey("InvoiceId");

                    b.HasOne("Data.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Data.Entities.OrderEmployees", b =>
                {
                    b.HasOne("Data.Entities.Employee", "Employee")
                        .WithMany("OrderEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Entities.Order", "Order")
                        .WithMany("OrderEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Order");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Data.Entities.PartnerUser", b =>
                {
                    b.HasOne("Data.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.Product", b =>
                {
                    b.HasOne("Data.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("ProductCategoryId");

                    b.Navigation("Partner");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("Data.Entities.ProductCategory", b =>
                {
                    b.HasOne("Data.Entities.ProductCategory", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentProductCategoryID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Data.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentCategory");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Data.Entities.ProductEmployees", b =>
                {
                    b.HasOne("Data.Entities.Employee", "Employee")
                        .WithMany("ProductEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Entities.Product", "Product")
                        .WithMany("ProductEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Partner", "Partner")
                        .WithMany("ProductEmployees")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Partner");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Data.Entities.ProductInventory", b =>
                {
                    b.HasOne("Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Data.Entities.ProductPrice", b =>
                {
                    b.HasOne("Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Data.Entities.UserRole", b =>
                {
                    b.HasOne("Data.Entities.SystemRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.Activity", b =>
                {
                    b.Navigation("ActivityEmployees");
                });

            modelBuilder.Entity("Data.Entities.Contact", b =>
                {
                    b.Navigation("ContactEmployees");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Data.Entities.Customer", b =>
                {
                    b.Navigation("CustomerEmployees");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Data.Entities.Employee", b =>
                {
                    b.Navigation("ActivityEmployees");

                    b.Navigation("ContactEmployees");

                    b.Navigation("CustomerEmployees");

                    b.Navigation("InvoiceEmployees");

                    b.Navigation("OrderEmployees");

                    b.Navigation("ProductEmployees");
                });

            modelBuilder.Entity("Data.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceEmployees");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Data.Entities.Order", b =>
                {
                    b.Navigation("OrderEmployees");
                });

            modelBuilder.Entity("Data.Entities.Partner", b =>
                {
                    b.Navigation("ActivityEmployees");

                    b.Navigation("ContactEmployees");

                    b.Navigation("CustomerEmployees");

                    b.Navigation("InvoiceEmployees");

                    b.Navigation("ProductEmployees");
                });

            modelBuilder.Entity("Data.Entities.Product", b =>
                {
                    b.Navigation("ProductEmployees");
                });

            modelBuilder.Entity("Data.Entities.ProductCategory", b =>
                {
                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
