name: Build and deploy Autuna ASP.NET Core Backend to Azure Web API Service

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Server/Server.csproj

      - name: Build with dotnet
        run: dotnet build Server/Server.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish with dotnet
        run: dotnet publish Server/Server.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ github.ref == 'refs/heads/develop' && 'Development' || 'Production' }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ github.ref == 'refs/heads/develop' && secrets.AZUREAPPSERVICE_CLIENTID_DEV || secrets.AZUREAPPSERVICE_CLIENTID_PROD }}
          tenant-id: ${{ github.ref == 'refs/heads/develop' && secrets.AZUREAPPSERVICE_TENANTID_DEV || secrets.AZUREAPPSERVICE_TENANTID_PROD }}
          subscription-id: ${{ github.ref == 'refs/heads/develop' && secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DEV || secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_PROD }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ github.ref == 'refs/heads/develop' && 'autuna-g7atefbyardqe9gt' || 'myapp-prod' }}
          slot-name: 'Production'
          package: .
