name: Build and deploy Autuna ASP.NET Core Backend to Azure Web App Service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Server/Server.csproj

      - name: Build with dotnet
        run: dotnet build Server/Server.csproj --configuration Release --no-restore

      - name: Build tests
        run: dotnet build Server.Tests/Server.Tests.csproj --configuration Release

      - name: Run tests
        run: dotnet test Server.Tests/Server.Tests.csproj --configuration Release --no-build --verbosity normal
        continue-on-error: true

      - name: Publish with dotnet
        run: dotnet publish Server/Server.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ github.ref == 'refs/heads/develop' && 'Development' || 'Production' }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B576AAC0C1574AC5B1F553CDBE6BA272 }}
          tenant-id: ${{  secrets.AZUREAPPSERVICE_TENANTID_9C69D4EED4054507AB781E27046DE807 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D3F84EC9F9B04CA88DE8FA704AFB87FC }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'autuna'
          slot-name: 'Production'
          package: .
