name: Build and deploy ASP.Net Core app to Azure Web App - autuna

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Check DOTNET_ROOT
        run: echo "DOTNET_ROOT is $DOTNET_ROOT"

      - name: Restore dependencies
        run: dotnet restore Server/Server.csproj

      - name: Build with dotnet
        run: dotnet build Server/Server.csproj --configuration Release --no-restore

      - name: Build tests
        run: dotnet build Server.Tests/Server.Tests.csproj --configuration Release

      - name: Run tests
        run: dotnet test Server.Tests/Server.Tests.csproj --configuration Release --no-build --verbosity normal
        continue-on-error: true

      - name: Publish with dotnet
        run: dotnet publish Server/Server.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Copy ServerLibrary Templates
        run: |
          mkdir -p ${{env.DOTNET_ROOT}}/myapp/ServerLibrary/Templates
          cp -r ServerLibrary/Templates/* ${{env.DOTNET_ROOT}}/myapp/ServerLibrary/Templates/
          ls -la ${{env.DOTNET_ROOT}}/myapp/ServerLibrary/Templates/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ github.ref == 'refs/heads/develop' && 'Development' || 'Production' }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Check Azure credentials
        run: |
          echo "Branch: ${GITHUB_REF}"
          echo "Client ID: ${{ secrets.AZUREAPPSERVICE_CLIENTID_69603B037955431C8DE25AF9EE54B6D3 }}"
          echo "Tenant ID: ${{ secrets.AZUREAPPSERVICE_TENANTID_F73FCCC454874E1596A8C0D638C4B2A9 }}"
          echo "Subscription ID: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1EAAA2C794B048B2B398BA7FB17DAE54 }}"
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_69603B037955431C8DE25AF9EE54B6D3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F73FCCC454874E1596A8C0D638C4B2A9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1EAAA2C794B048B2B398BA7FB17DAE54 }}
          enable-AzPSSession: false
          environment: azurecloud
          allow-no-subscriptions: false

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: autuna
          slot-name: Production
          package: .
